Repository nanafox/AirBnB_clone_v4, pull requests merged in 2024-05, with the labels that each got.

#1 Add Flask development server scripts and update dependencies
  .gitignore
  README.md
  api/v1/app.py
  console.py
  db-flask
  fs-flask
  models/amenity.py
  models/base_model.py
  models/city.py
  models/engine/file_storage.py
  models/place.py
  models/review.py
  models/state.py
  models/user.py
  populate_storage.py
  requirements.txt
Labels: documentation, enhancement

#2 Web dynamic 01
  web_dynamic/0-hbnb.py
  web_dynamic/__init__.py
  web_dynamic/static/images/icon.png
  web_dynamic/static/images/icon_bath.png
  web_dynamic/static/images/icon_bed.png
  web_dynamic/static/images/icon_group.png
  web_dynamic/static/images/logo.png
  web_dynamic/static/styles/3-footer.css
  web_dynamic/static/styles/3-header.css
  web_dynamic/static/styles/4-common.css
  web_dynamic/static/styles/6-filters.css
  web_dynamic/static/styles/8-places.css
  web_dynamic/static/styles/w3c_validator.py
  web_dynamic/templates/0-hbnb.html
Labels: enhancement

#3 Refactor Flask development server script
  db-flask
  fs-flask
  populate_storage.py
Labels: bug, enhancement

#4 Refactor Flask app and add time lapse transition for popover element
  web_dynamic/1-hbnb.py
  web_dynamic/static/scripts/1-hbnb.js
  web_dynamic/static/styles/6-filters.css
  web_dynamic/templates/1-hbnb.html
Labels: enhancement

#7 Update places information retrieval to use frontend
  web_dynamic/3-hbnb.py
  web_dynamic/static/scripts/3-hbnb.js
  web_dynamic/templates/3-hbnb.html
Labels: enhancement

#8 Update automation script and add 4-hbnb.html template with necessary dependencies
  db-flask
  populate_storage.py
  web_dynamic/4-hbnb.py
  web_dynamic/static/scripts/4-hbnb.js
  web_dynamic/static/styles/6-filters.css
  web_dynamic/templates/4-hbnb.html
Labels: enhancement
